spring:
  datasource:
    url: jdbc:mysql://localhost:3306/makoffea
    username: root
    password: 12y@n13@rc3b@l
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ACCOUNT-SERVICE



#EurekaServerClientConnection

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


