spring:
  datasource:
    url: jdbc:mysql://localhost:3306/makoffea
    username: root
    password: 12y@n13@rc3b@l
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: PRODUCT-SERVICE



server:
  port: 8082
eureka:
  client:
    seviceUrl:
      defaultZone: http://localhost:8761/eureka/