#server:
#  port: 8761
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false

spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

